[ETFE-1588] add ChooseShortageExcessItem page
hmrc/emcs-tfe-explain-shortage-excess-frontend pull request #23
Opened 2023-08-08 16:51 UTC by james-work-account

- [ETFE-1591] Adding the Item-Amount page.
- [ETFE-1591] Add scoverageOff to views and correct name of model
- [ETFE-1588] WIP choose-shortage-excess-item
- [ETFE-1588] added ChooseShortageExcessItem page

2023-08-08 18:58 UTC, james-work-account commented
Changing to draft as I've noticed a couple of inconsistencies between the prototype/copydeck/ticket which I want ironing out before it's merged. Will reopen once they're sorted out

2023-08-09 07:13 UTC, MJCallahanPage requested changes
Some minor refactors and a Content Design question.

2023-08-09 07:13 UTC, MJCallahanPage commented on conf/messages.cy
> +chooseShortageExcessItem.heading = What''s wrong with item {0}?
I think these should be single curly quotes, which is better typography. This was raised on a previous project by a content writer. Maybe it's something we need to check with Clare and Tom but I've been changing mine.

This was the old article the previous designer sent to me:
https://smartquotesforsmartpeople.com/

2023-08-09 14:13 UTC, MJCallahanPage submitted a review, later dismissed
LGTM 🟢  - just one small conflict on appRoutes.

2023-08-10 11:35 UTC, grahampaulcook approved these changes

2023-08-10 12:11 UTC, merged